--- #YAML:1.0
name:               Term-ExtendedColor-Xresources
version:            0.054
abstract:           Get, set and modify X resources
author:
    - Magnus Woldrich <trapd00r@trapd00r.se>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Term::ReadKey:  0
    Test::More:     0
resources:
    bugtracker:  https://github.com/trapd00r/Term-ExtendedColor-Xresources/issues
    repository:  https://github.com/trapd00r/Term-ExtendedColor-Xresources
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
