---
abstract: 'Get, set and modify X resources'
author:
  - 'Magnus Woldrich <trapd00r@trapd00r.se>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-ExtendedColor-Xresources
no_index:
  directory:
    - t
    - inc
requires:
  Term::ReadKey: 0
  Test::More: 0
resources:
  bugtracker: https://github.com/trapd00r/Term-ExtendedColor-Xresources/issues
  repository: https://github.com/trapd00r/Term-ExtendedColor-Xresources
version: 0.072
